// Centralised search index — all searchable items on the site

export const searchIndex = [
  // ── BED ROOM ──────────────────────────────────────────────────────────────
  {
    id: "single-bed",
    name: "Single Bed",
    description: "Perfect for individual sleepers and smaller spaces",
    category: "Bed Room",
    slug: "/beds/single",
  },
  {
    id: "double-bed",
    name: "Double Bed",
    description: "Comfortable space for couples and guest rooms",
    category: "Bed Room",
    slug: "/beds/double",
  },
  {
    id: "queen-bed",
    name: "Queen Bed",
    description: "The most popular size with extra room to stretch",
    category: "Bed Room",
    slug: "/beds/queen",
  },
  {
    id: "king-bed",
    name: "King Bed",
    description: "Maximum comfort and space for luxury sleeping",
    category: "Bed Room",
    slug: "/beds/king",
  },
  {
    id: "bunk-bed",
    name: "Bunk Beds",
    description: "Space-saving beds for kids and guest rooms",
    category: "Bed Room",
    slug: "/gallery?category=BED+ROOM",
  },
  {
    id: "daybed",
    name: "Daybeds",
    description: "Versatile beds that double as seating",
    category: "Bed Room",
    slug: "/gallery?category=BED+ROOM",
  },
  {
    id: "platform-bed",
    name: "Platform Beds",
    description: "Low-profile modern beds with sleek frames",
    category: "Bed Room",
    slug: "/gallery?category=BED+ROOM",
  },
  {
    id: "sofa-bed",
    name: "Sofa cum Beds",
    description: "Convertible sofa that folds into a bed",
    category: "Bed Room",
    slug: "/gallery?category=BED+ROOM",
  },

  // ── LIVING ROOM ───────────────────────────────────────────────────────────
  {
    id: "sofas-couches",
    name: "Sofas & Couches",
    description: "Stylish sofas for your living room",
    category: "Living Room",
    slug: "/gallery?category=LIVING+ROOM",
  },
  {
    id: "sectionals",
    name: "Sectionals",
    description: "Large sectional sofas for spacious rooms",
    category: "Living Room",
    slug: "/gallery?category=LIVING+ROOM",
  },
  {
    id: "loveseats",
    name: "Loveseats",
    description: "Compact two-seater sofas",
    category: "Living Room",
    slug: "/gallery?category=LIVING+ROOM",
  },
  {
    id: "armchairs-living",
    name: "Armchairs",
    description: "Elegant armchairs for living rooms",
    category: "Living Room",
    slug: "/gallery?category=LIVING+ROOM",
  },
  {
    id: "recliners",
    name: "Recliners",
    description: "Relaxing recliner chairs",
    category: "Living Room",
    slug: "/gallery?category=LIVING+ROOM",
  },
  {
    id: "coffee-tables",
    name: "Coffee Tables",
    description: "Centrepiece tables for your living room",
    category: "Living Room",
    slug: "/gallery?category=LIVING+ROOM",
  },
  {
    id: "tv-stands",
    name: "TV Stands",
    description: "Modern TV units and media consoles",
    category: "Living Room",
    slug: "/gallery?category=LIVING+ROOM",
  },
  {
    id: "side-tables",
    name: "Side Tables",
    description: "Handy side and end tables",
    category: "Living Room",
    slug: "/gallery?category=LIVING+ROOM",
  },

  // ── DINING ROOM ───────────────────────────────────────────────────────────
  {
    id: "dining-table-12",
    name: "Twelve Seater Dining Tables",
    description: "Grand dining tables for large families",
    category: "Dining Room",
    slug: "/gallery?category=DINING+ROOM",
  },
  {
    id: "dining-table-10",
    name: "Ten Seater Dining Tables",
    description: "Spacious dining tables for 10 people",
    category: "Dining Room",
    slug: "/gallery?category=DINING+ROOM",
  },
  {
    id: "dining-table-8",
    name: "Eight Seater Dining Tables",
    description: "Dining tables for 8 people",
    category: "Dining Room",
    slug: "/gallery?category=DINING+ROOM",
  },
  {
    id: "dining-table-6",
    name: "Six Seater Dining Tables",
    description: "Dining tables for 6 people",
    category: "Dining Room",
    slug: "/gallery?category=DINING+ROOM",
  },
  {
    id: "dining-table-4",
    name: "Four Seater Dining Tables",
    description: "Compact dining tables for 4 people",
    category: "Dining Room",
    slug: "/gallery?category=DINING+ROOM",
  },
  {
    id: "dining-chairs",
    name: "Dining Chairs",
    description: "Matching chairs for your dining table",
    category: "Dining Room",
    slug: "/gallery?category=DINING+ROOM",
  },
  {
    id: "sideboard",
    name: "Side Board",
    description: "Elegant sideboards for dining rooms",
    category: "Dining Room",
    slug: "/gallery?category=DINING+ROOM",
  },
  {
    id: "crockery-unit",
    name: "Crockery Unit",
    description: "Display and store your crockery in style",
    category: "Dining Room",
    slug: "/gallery?category=DINING+ROOM",
  },
  {
    id: "dining-benches",
    name: "Dining Benches",
    description: "Benches for dining rooms",
    category: "Dining Room",
    slug: "/gallery?category=DINING+ROOM",
  },
  {
    id: "bar-units",
    name: "Bar Units, Bar Cabinets & Trolleys",
    description: "Stylish bar furniture for home",
    category: "Dining Room",
    slug: "/gallery?category=DINING+ROOM",
  },
  {
    id: "bar-stools",
    name: "Bar Stools & Chairs",
    description: "Bar stools and high chairs",
    category: "Dining Room",
    slug: "/gallery?category=DINING+ROOM",
  },

  // ── SOFA ──────────────────────────────────────────────────────────────────
  {
    id: "sofa-couch",
    name: "Sofas & Couches",
    description: "Premium sofas and couches",
    category: "Sofa",
    slug: "/gallery?category=SOFA",
  },
  {
    id: "sofa-sectional",
    name: "Sectionals",
    description: "L-shaped and U-shaped sectional sofas",
    category: "Sofa",
    slug: "/gallery?category=SOFA",
  },
  {
    id: "loveseat-sofa",
    name: "Loveseats",
    description: "Two-seater loveseats",
    category: "Sofa",
    slug: "/gallery?category=SOFA",
  },
  {
    id: "armchair-sofa",
    name: "Armchairs",
    description: "Classic and modern armchairs",
    category: "Sofa",
    slug: "/gallery?category=SOFA",
  },
  {
    id: "recliner-sofa",
    name: "Recliners",
    description: "Motorised and manual recliners",
    category: "Sofa",
    slug: "/gallery?category=SOFA",
  },

  // ── OUTDOOR ───────────────────────────────────────────────────────────────
  {
    id: "outdoor-tables",
    name: "Outdoor Tables",
    description: "Weather-resistant tables for outdoors",
    category: "Outdoor",
    slug: "/gallery?category=OUTDOOR",
  },
  {
    id: "outdoor-chairs",
    name: "Outdoor Chairs",
    description: "Durable chairs for gardens and patios",
    category: "Outdoor",
    slug: "/gallery?category=OUTDOOR",
  },
  {
    id: "outdoor-sets",
    name: "Outdoor Sets",
    description: "Complete outdoor furniture sets",
    category: "Outdoor",
    slug: "/gallery?category=OUTDOOR",
  },
  {
    id: "outdoor-lamps",
    name: "Outdoor Lamps",
    description: "Lighting for outdoor spaces",
    category: "Outdoor",
    slug: "/gallery?category=OUTDOOR",
  },

  // ── ANTIQUE FURNITURE ─────────────────────────────────────────────────────
  {
    id: "antique-tables",
    name: "Antique Tables",
    description: "Handcrafted antique-style tables",
    category: "Antique Furniture",
    slug: "/gallery?category=ANTIQUE+FURNITURE",
  },
  {
    id: "antique-chairs",
    name: "Antique Chairs",
    description: "Classic antique-style chairs",
    category: "Antique Furniture",
    slug: "/gallery?category=ANTIQUE+FURNITURE",
  },
  {
    id: "antique-sets",
    name: "Antique Sets",
    description: "Complete antique furniture sets",
    category: "Antique Furniture",
    slug: "/gallery?category=ANTIQUE+FURNITURE",
  },
  {
    id: "antique-lamps",
    name: "Antique Lamps",
    description: "Vintage-style lamps and lighting",
    category: "Antique Furniture",
    slug: "/gallery?category=ANTIQUE+FURNITURE",
  },

  // ── HOME DECOR ────────────────────────────────────────────────────────────
  {
    id: "home-decor",
    name: "Home Decor",
    description: "Beautiful home decor pieces",
    category: "Home Decor",
    slug: "/gallery?category=HOME+DECOR",
  },
  {
    id: "ceiling-lights",
    name: "Hanging Lights & Ceiling Lights",
    description: "Pendant and ceiling light fixtures",
    category: "Home Decor",
    slug: "/gallery?category=HOME+DECOR",
  },
  {
    id: "wall-lights",
    name: "Wall Mounted Lights",
    description: "Elegant wall sconces and lights",
    category: "Home Decor",
    slug: "/gallery?category=HOME+DECOR",
  },
  {
    id: "table-lights",
    name: "Table Lights",
    description: "Stylish table lamps",
    category: "Home Decor",
    slug: "/gallery?category=HOME+DECOR",
  },
  {
    id: "floor-lights",
    name: "Floor Lights",
    description: "Floor-standing lamps",
    category: "Home Decor",
    slug: "/gallery?category=HOME+DECOR",
  },
  {
    id: "wall-decor-lights",
    name: "Wall Decor with Lights",
    description: "Decorative wall pieces with lighting",
    category: "Home Decor",
    slug: "/gallery?category=HOME+DECOR",
  },
  {
    id: "wall-decor",
    name: "Wall Decor",
    description: "Artwork and decorative wall pieces",
    category: "Home Decor",
    slug: "/gallery?category=HOME+DECOR",
  },
  {
    id: "wall-mirrors",
    name: "Wall Mounted Mirrors",
    description: "Framed wall mirrors",
    category: "Home Decor",
    slug: "/gallery?category=HOME+DECOR",
  },
  {
    id: "floor-mirrors",
    name: "Floor Mounted Mirrors",
    description: "Full-length floor mirrors",
    category: "Home Decor",
    slug: "/gallery?category=HOME+DECOR",
  },
  {
    id: "full-body-mirrors",
    name: "Full Body Mirrors",
    description: "Full body length mirrors",
    category: "Home Decor",
    slug: "/gallery?category=HOME+DECOR",
  },

  // ── CHAIRS ────────────────────────────────────────────────────────────────
  {
    id: "office-chairs",
    name: "Office Chairs",
    description: "Ergonomic chairs for home and office",
    category: "Chairs",
    slug: "/gallery?category=CHAIRS",
  },
  {
    id: "armchairs",
    name: "Armchairs",
    description: "Comfortable armchairs for any room",
    category: "Chairs",
    slug: "/gallery?category=CHAIRS",
  },
  {
    id: "bar-stools-chairs",
    name: "Bar Stools",
    description: "Counter and bar height stools",
    category: "Chairs",
    slug: "/gallery?category=CHAIRS",
  },
  {
    id: "chair-pads",
    name: "Chair Pads",
    description: "Cushioned pads for chairs",
    category: "Chairs",
    slug: "/gallery?category=CHAIRS",
  },
  {
    id: "chaise-lounges",
    name: "Chaise Lounges",
    description: "Luxurious chaise lounge chairs",
    category: "Chairs",
    slug: "/gallery?category=CHAIRS",
  },
  {
    id: "desk-chairs",
    name: "Desk Chairs",
    description: "Adjustable desk and study chairs",
    category: "Chairs",
    slug: "/gallery?category=CHAIRS",
  },
  {
    id: "dining-chairs-cat",
    name: "Dining Chairs",
    description: "Stylish chairs for dining tables",
    category: "Chairs",
    slug: "/gallery?category=CHAIRS",
  },
];
